name: postly
description: A modern social media platform for sharing moments, ideas, and inspiration.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  http: ^1.1.0
  get_storage: ^2.1.1
  image_picker: ^1.0.4
  cached_network_image: ^3.3.0
  flutter_image_compress: ^1.1.3
  path_provider: ^2.1.0
  permission_handler: ^10.4.0
  intl: ^0.18.1
  pull_to_refresh: ^2.0.0
  flutter_staggered_animations: ^1.1.1
  fluttertoast: ^8.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true